Assignment 2

## Part 1 : Data Acquisition

### Step 1: Downloading the 'Kaggle 5000 Movie Dataset'

In [1]:
import urllib.request # instead of 'import urllib in Python 2'
import os

if not os.path.exists('./data'):
    os.makedirs('./data')
    
kaggle_url = "https://users.encs.concordia.ca/~gregb/home/comp499data/movie_metadata.csv"
if not os.path.exists('.data/kaggle_dataset.csv'):
    response = urllib.request.urlretrieve(kaggle_url, './data/kaggle_dataset.csv')
    
    # had to change 'urllib.urlretrive' for 'urllib.request.urlretrieve'

### Step 2: Downloading the 'IMDB Plain Text Data'

In [2]:
import gzip

# Obtaining IMDB's text files
imdb_url_prefix = 'https://users.encs.concordia.ca/~gregb/home/comp499data/'
imdb_files_list = ['genres.list.gz', 'ratings.list.gz']
for name in imdb_files_list:
    if not os.path.exists('./data/' + name):
        response = urllib.request.urlretrieve(imdb_url_prefix + name, './data/' + name)
        urllib.request.urlcleanup()   # urllib fails to download two files from a ftp source. This fixes the bug!
        with gzip.open('./data/' + name) as comp_file, open('./data/' + name[:-3], 'w') as reg_file:
            file_content = comp_file.read()
            reg_file.write(file_content.decode("iso-8859-1"))
            
            
# had to change all calls 'urllib' in Python 2 to Python 3's 'urllib.request'
# also had to add 'decode(iso-8859-1")'

### Step 3: Downloading the 'IMDB Prepared Data'

In [3]:
imdb_url = "https://users.encs.concordia.ca/~gregb/home/comp499data/imdb_dataset.csv"
if not os.path.exists('./data/imdb_dataset.csv'): 
    response = urllib.request.urlretrieve(imdb_url, './data/imdb_dataset.csv')

## Part 2: Data Extraction

#### Content of the "ratings.list" data file

In [4]:
path = "./data/ratings.list"
with open(path) as myfile:
    head = [next(myfile) for x in range(38)]
print (''.join(head[28:38]))   # skipping the first 28 lines as they are descriptive headers

      0000000125  1888533   9.2  The Shawshank Redemption (1994)
      0000000125  1289428   9.2  The Godfather (1972)
      0000000124  889607   9.0  The Godfather: Part II (1974)
      0000000124  1864164   9.0  The Dark Knight (2008)
      0000000133  518449   8.9  12 Angry Men (1957)
      0000000133  971107   8.9  Schindler's List (1993)
      0000000123  1477112   8.9  Pulp Fiction (1994)
      0000000124  1349449   8.9  The Lord of the Rings: The Return of the King (2003)
      0000000123  559468   8.8  Il buono, il brutto, il cattivo (1966)
      0000000133  1513600   8.8  Fight Club (1999)

#### Content of the "genres.list" data file

In [5]:
path = "./data/genres.list"
with open(path) as myfile:
    head = [next(myfile) for x in range(392)]
print (''.join(head[382:392]))   # skipping the first 382 lines as they are descriptive header

==================

"!Next?" (1994)						Documentary
"#1 Single" (2006)					Reality-TV
"#15SecondScare" (2015)					Horror
"#15SecondScare" (2015)					Short
"#15SecondScare" (2015)					Thriller
"#15SecondScare" (2015) {Who Wants to Play with the Rabbit? (#1.2)}	Drama
"#15SecondScare" (2015) {Who Wants to Play with the Rabbit? (#1.2)}	Horror
"#15SecondScare" (2015) {Who Wants to Play with the Rabbit? (#1.2)}	Short

### Step 1: Extracting the information from "genres.list"

In [6]:
import re
import pandas as pd

with open("./data/genres.list") as genres_file:
    raw_content = genres_file.readlines()
    genres_list = []
    content = raw_content[382:]
    for line in content:
        m = re.match(r'"?(.*[^"])"? \(((?:\d|\?){4})(?:/\w*)?\).*\s((?:\w|-)+)', line.strip())
        if m is None: continue
        genres_list.append([m.group(1), m.group(2), m.group(3)])
    genres_data = pd.DataFrame(genres_list, columns=['movie', 'year', 'genre'])
    
genres_data

                                                     movie  year        genre
0                                                   !Next?  1994  Documentary
1                                                #1 Single  2006   Reality-TV
2                                           #15SecondScare  2015       Horror
3                                           #15SecondScare  2015        Short
4                                           #15SecondScare  2015     Thriller
5                                           #15SecondScare  2015        Drama
6                                           #15SecondScare  2015       Horror
7                                           #15SecondScare  2015        Short
8                                           #15SecondScare  2015     Thriller
9                                        #1MinuteNightmare  2014       Horror
10                                                   #2G1S  2016        Crime
11                                          #2WheelzNHeelz  2017   Reality-TV
12                                         #30Nods Trailer  2016        Drama
13                                                 #30Nods  2016        Drama
14                                                  #4Hire  2017       Comedy
15                                             #7DaysLater  2013       Comedy
16                                                  #ATown  2014       Comedy
17                                             #ActorsLife  2016    Talk-Show
18                                                #Actress  2014       Comedy
19                                              #Adulthood  ????       Comedy
20                                               #Adulting  2016       Comedy
21                                               #Adulting  2016       Comedy
22                                               #AuVolant  2016       Comedy
23                                          #Awkward Dates  2016       Comedy
24                                        #AwkwardMornings  2014       Comedy
25                                               #Bandcamp  2014      Musical
26                                         #BedTimeBitchin  2014       Comedy
27                                                #Besties  2014       Comedy
28                                              #Bikerlive  2014   Reality-TV
29                                              #BlackLove  2015   Reality-TV
...                                                    ...   ...          ...
2658911                          è solo un nastro che gira  2017      Romance
2658912                          è solo un nastro che gira  2017        Short
2658913                                éX-Driver the Movie  2002       Action
2658914                                éX-Driver the Movie  2002    Animation
2658915                  éX-Driver: Nina & Rei Danger Zone  2002    Animation
2658916                  éX-Driver: Nina & Rei Danger Zone  2002        Short
2658917                                       échec et mat  2016        Short
2658918                                                 él  2001        Adult
2658919                                                 él  2001    Animation
2658920                                                 él  2001      Mystery
2658921                                                 él  2001       Sci-Fi
2658922                                                 él  2001     Thriller
2658923                                                êMe  2014        Drama
2658924                                                êMe  2014        Short
2658925                                           ìCàcaro!  2002        Short
2658926                  ìMaten a ese hijo de la chingada!  2008       Action
2658927  íslenska, on the Road to Unearth Iceland's Sec...  2007    Adventure
2658928  íslenska, on the Road to Unearth Iceland's Sec...  2007        Short
2658929                                             împetu  2017  Documentary
2658930                                                  ö  2012    Animation
2658931                                                  ö  2012        Short
2658932                                         öregHarcos  2016  Documentary
2658933                                         öregHarcos  2016        Short
2658934                                      öregHarcos II  2017  Documentary
2658935                                      öregHarcos II  2017        Short
2658936                                           überRICH  2017       Comedy
2658937                                           überRICH  2017        Short
2658938                                                 üç  2012    Adventure
2658939                                                 üç  2012       Comedy
2658940                                                 üç  2012        Short

[2658941 rows x 3 columns]

In [7]:
with open("./data/ratings.list") as ratings_file:
    raw_content = ratings_file.readlines()
    ratings_list = []
    content = raw_content[28:]
    for line in content:
        m = re.match(r'(?:\d|\.|\*){10}\s+\d+\s+(1?\d\.\d)\s"?(.*[^"])"? \(((?:\d|\?){4})(?:/\w*)?\)', line.strip())
        if m is None: continue
        ratings_list.append([m.group(2), m.group(3), m.group(1)])
    ratings_data = pd.DataFrame(ratings_list, columns=['movie', 'year', 'rating'])
    
ratings_data

                                                    movie  year rating
0                                The Shawshank Redemption  1994    9.2
1                                           The Godfather  1972    9.2
2                                  The Godfather: Part II  1974    9.0
3                                         The Dark Knight  2008    9.0
4                                            12 Angry Men  1957    8.9
5                                        Schindler's List  1993    8.9
6                                            Pulp Fiction  1994    8.9
7           The Lord of the Rings: The Return of the King  2003    8.9
8                         Il buono, il brutto, il cattivo  1966    8.8
9                                              Fight Club  1999    8.8
10       The Lord of the Rings: The Fellowship of the ...  2001    8.8
11                                           Forrest Gump  1994    8.7
12         Star Wars: Episode V - The Empire Strikes Back  1980    8.7
13                                              Inception  2010    8.7
14                  The Lord of the Rings: The Two Towers  2002    8.7
15                        One Flew Over the Cuckoo's Nest  1975    8.7
16                                             Goodfellas  1990    8.7
17                                             The Matrix  1999    8.7
18                                   Shichinin no samurai  1954    8.6
19                                              Star Wars  1977    8.6
20                                         Cidade de Deus  2002    8.6
21                                                  Se7en  1995    8.6
22                               The Silence of the Lambs  1991    8.6
23                                  It's a Wonderful Life  1946    8.6
24                                        La vita è bella  1997    8.6
25                                     The Usual Suspects  1995    8.6
26                                                   Léon  1994    8.5
27                                    Saving Private Ryan  1998    8.5
28                          Sen to Chihiro no kamikakushi  2001    8.5
29                                                   Coco  2017    8.5
...                                                   ...   ...    ...
789385                                        Üç garipler  1957    6.7
789386                                        Üç halka 25  1986    5.5
789387                                      Üç kagitçilar  1976    7.2
789388                               Üç kardese bir gelin  1965    5.8
789389                                     Üç kisilik ask  2004    7.2
789390                                 Üç kursunluk opera  1995    6.4
789391                                         Üç sevgili  1972    5.9
789392                         Üç süpermen olimpiyatlarda  1984    4.7
789393                                      Üç tatli bela  1979    4.2
789394                             Üç tekerlekli bisiklet  1962    7.6
789395                                     Üç öfkeli genç  1963    5.7
789396                            Üç, Iki, Bir... Kestik!  2014    4.3
789397                                           Üçte bir  2009    6.9
789398                                       Üçüncü Sayfa  1999    7.5
789399                            Üçüncü Selim'in Gözdesi  1950    7.3
789400                                         Üçüncü göz  1988    7.2
789401                                Üçünüzü de mihlarim  1965    6.2
789402                               Þegar Kanínur Fljúga  2011    8.5
789403                                   Þegar það gerist  1998    5.6
789404                                      Þetta Reddast  2013    4.1
789405                                Þetta er ekkert mál  2006    8.7
789406                                            Þrestir  2015    6.9
789407                                       Þriðja nafni  2003    6.9
789408                                          Þröng sýn  2005    7.6
789409                                           Þú og ég  2015    6.8
789410                                             à deux  2017    8.8
789411                                             ärtico  2014    7.0
789412                                éX-Driver the Movie  2002    5.4
789413                                                 él  2001    6.2
789414                                                  ö  2012    6.8

[789415 rows x 3 columns]

## Part 3: Data Profiling and Cleaning

### Step 1: Loading the “Kaggle 5000 Movie Dataset”

In [8]:
import pandas as pd

# Loading the Kaggle dataset from the .csv file (kaggle_dataset.csv)
kaggle_data = pd.read_csv('./data/kaggle_dataset.csv')
kaggle_data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### Step 2: Calculating Some Basic Statistics (Profiling)

In [9]:
print ('Number of movies in kaggle_data: {}'.format(kaggle_data.shape[0]))
print ('Number of movies in genres_data: {}'.format(genres_data.shape[0]))
print ('Number of movies in ratings_data: {}'.format(ratings_data.shape[0]))

Number of movies in kaggle_data: 5043
Number of movies in genres_data: 2658941
Number of movies in ratings_data: 789415

### Step 3: Dealing with duplicates (cleaning)

In [10]:
print ('Number of duplicates in kaggle_data: {}'.format(
    sum(kaggle_data.duplicated(subset=['movie_title', 'title_year'], keep=False))))
print ('Number of duplicates in genres_data: {}'.format(
    sum(genres_data.duplicated(subset=['movie', 'year'], keep=False))))
print ('Number of duplicates in ratings_data: {}'.format(
    sum(ratings_data.duplicated(subset=['movie', 'year'], keep=False))))

Number of duplicates in kaggle_data: 241
Number of duplicates in genres_data: 2031322
Number of duplicates in ratings_data: 342815

In [11]:
# kaggle_data.duplicated(subset=['movie_title', 'title_year'], keep=False)

# help(pd.DataFrame.duplicated)

# print all the duplicated elements indexes   
# dupli = kaggle_data.duplicated(subset=['movie_title', 'title_year'], keep=False)
# for idx, val in enumerate(dupli):
#    if val == True:
#        print(idx)

In [12]:
kaggle_data = kaggle_data.drop_duplicates(subset=['movie_title', 'title_year'], keep='first').copy()
genres_data = genres_data.drop_duplicates(subset=['movie', 'year'], keep='first').copy()
ratings_data = ratings_data.drop_duplicates(subset=['movie', 'year'], keep='first').copy()

### Step 4: Normalizing the text (cleaning)

The key attribute that we will use to integrate our movie datasets is the movie titles. So it is important to normalize these titles. The following code snippet makes all movie titles lower case, and then removes certain characters such as “‘” and “?”, and replaces some other special characters (e.g., “&” is replaced with “and”)

In [13]:
def preprocess_title(title):
    title = title.lower()
    title = title.replace(',', ' ')
    title = title.replace("'", '')    
    title = title.replace('&', 'and')
    title = title.replace('?', '')
    # title = title.decode('utf-8', 'ignore')  in Python 3, all str is unicode object
    return title.strip()

kaggle_data['norm_movie_title'] = kaggle_data['movie_title'].map(preprocess_title)
genres_data['norm_movie'] = genres_data['movie'].map(preprocess_title)
ratings_data['norm_movie'] = ratings_data['movie'].map(preprocess_title)

### Step 5: Looking at a few samples

In [14]:
kaggle_data.sample(3, random_state=0)

# pandas.DataFrame.sample: Return a random sample of items from an axis of object
# random_state: for reproducibility

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,norm_movie_title
4422,Color,Simeon Rice,6.0,93.0,6.0,56.0,Lisa Brave,393.0,NaN,Action|Horror|Thriller,...,English,USA,R,1500000.0,2014.0,191.0,5.5,2.35,307,unsullied
1022,Color,Doug Liman,214.0,108.0,218.0,405.0,Ty Burrell,6000.0,9528092.0,Biography|Drama|Thriller,...,English,USA,PG-13,22000000.0,2010.0,3000.0,6.8,2.35,9000,fair game
3631,Color,Jonathan Levine,147.0,99.0,129.0,362.0,Aaron Yoo,976.0,2077046.0,Comedy|Drama|Romance,...,English,USA,R,6000000.0,2008.0,617.0,7.0,2.35,0,the wackness

The title_year attribute is stored as floats (i.e., rational numbers).
We can add another cleaning step to transform the title_year into strings and replace the missing title years with symbol “?”.

In [82]:
def preprocess_year(year):
    if pd.isnull(year):
        return '?'
    else:
        return str(int(year))

kaggle_data['norm_title_year'] = kaggle_data['title_year'].map(preprocess_year)
kaggle_data.head()

# pandas.core.series.Series.map : Map values of Series using input correspondence (which can be a dict, Series, or function)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,norm_movie_title,norm_title_year,id,mixture
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,237000000,2009.0,936.0,7.9,1.78,33000,avatar,2009,0,avatar 2009 237000000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,300000000,2007.0,5000.0,7.1,2.35,0,pirates of the caribbean: at worlds end,2007,1,pirates of the caribbean: at worlds end 2007 300000000
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,245000000,2015.0,393.0,6.8,2.35,85000,spectre,2015,2,spectre 2015 245000000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,250000000,2012.0,23000.0,8.5,2.35,164000,the dark knight rises,2012,3,the dark knight rises 2012 250000000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,12.0,7.1,NaN,0,star wars: episode vii - the force awakens,?,4,NaN

## Part 4: Data Matching & Merging

### Step 1: Integrating the “IMDB Plain Text Data” files

Note that both ratings_data and genres_data dataframes contain data that come from the same source (i.e., “the IMDB Plain Text data”). Thus, we assume that there are no inconsistencies between the data stored in these dataframe and to combine them, all we need to do is to match the entries that share the same title and production year. This simple “exact match” can be done simply using dataframes.

In [83]:
brief_imdb_data = pd.merge(ratings_data, genres_data, how='inner', on=['norm_movie', 'year'])
brief_imdb_data.head()

# inner join

,movie_x,year,rating,norm_movie,movie_y,genre
0,The Shawshank Redemption,1994,9.2,the shawshank redemption,The Shawshank Redemption,Crime
1,The Godfather,1972,9.2,the godfather,The Godfather,Crime
2,The Godfather: Part II,1974,9.0,the godfather: part ii,The Godfather: Part II,Crime
3,The Dark Knight,2008,9.0,the dark knight,The Dark Knight,Action
4,12 Angry Men,1957,8.9,12 angry men,12 Angry Men,Crime

We refer to the dataset created above as the brief_imdb_data since it only contains two attributes (namely, genre and rating). Henceforth, we are going to use a richer version of the IMDB dataset which we created by integrating a number of files from the “IMDB Plain Text Data”. If you have completed the first part of this tutorial, then this dataset is already downloaded and stored in “imdb_dataset.csv” under the “data” folder. The following code snippet loads this dataset, does preprocessing on the title and production year of movies, removes the duplicates as before, and prints the size of the dataset.

In [84]:
# reading the new IMDB dataset
imdb_data = pd.read_csv('./data/imdb_dataset.csv')
# let's normlize the title as we did in Part 3 of the tutorial
imdb_data['norm_title'] = imdb_data['title'].map(preprocess_title) #functions defined precedently
imdb_data['norm_year'] = imdb_data['year'].map(preprocess_year)
imdb_data = imdb_data.drop_duplicates(subset=['norm_title', 'norm_year'], keep='first').copy()
imdb_data.shape

(869178, 27)

### Step 2: Integrating the Kaggle and IMDB datasets

A simple approach to integrate the two datasets is to simply join entries that share the same movie title and year of production.

In [18]:
data_attempt1 = pd.merge(imdb_data, kaggle_data, how='inner', left_on=['norm_title', 'norm_year'], right_on=['norm_movie_title', 'norm_title_year'])
data_attempt1.shape

(4248, 57)

But given that IMDB and Kaggle datasets are collected from different sources, chances are that the name of a movie would be slightly different in these datasets (e.g. “Wall.E” vs “WallE”). To be able to find such matches, one can look at the similarity of movie titles and consider title with high similarity to be the same entity. BigGorilla provides a python pacakge named py_stringsimjoin for doing similarity join across two datasets. The following code snippet uses the py_stringsimjoin to match all the titles that have an edit distance of one or less (i.e., there is at most one character that needs to be changed/added/removed to make both titles identical). Once the similarity join is complete, it only selects the title pairs that are produced in the same year.

In [20]:
import py_stringsimjoin as ssj
    # had to run: pip install py-stringsimjoin
    # consider title with high similarity to be the same entity
import py_stringmatching as sm
    # had to run:  pip install py_entitymatching

imdb_data['id'] = range(imdb_data.shape[0])
kaggle_data['id'] = range(kaggle_data.shape[0])
similar_titles = ssj.edit_distance_join(imdb_data, kaggle_data, 'id', 'id', 'norm_title','norm_movie_title', l_out_attrs=['norm_title', 'norm_year'],r_out_attrs=['norm_movie_title', 'norm_title_year'], threshold=1)
# selecting the entries that have the same production year
data_attempt2 = similar_titles[similar_titles.r_norm_title_year == similar_titles.l_norm_year]
data_attempt2.shape

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:49

(4679, 8)

We can see that using the similarity join 4,689 titles were matched. Let’s look at some of the titles that are matched by the similarity join but are not identical.

In [86]:
# check similarity joins

data_attempt2[data_attempt2.l_norm_title != data_attempt2.r_norm_movie_title].head()

,_id,l_id,r_id,l_norm_title,l_norm_year,r_norm_movie_title,r_norm_title_year,_sim_score
145,145,852736,46,world war v,2013,world war z,2013,1.0
175,175,281649,56,grave,2012,brave,2012,1.0
243,243,816188,67,upe,2009,up,2009,1.0
250,250,817366,67,ut,2009,up,2009,1.0
265,265,316745,70,hug,2011,hugo,2011,1.0

### Step 3: Using Magellan for Data Matching

#### Substep A: Finding a candidate set (Blocking)

The goal of this step is to limit the number of pairs that we consider as potential matches using a simple heuristic. For this task, we can create a new column in each dataset that combines the values of important attributes into a single string (which we call the mixture). Then, we can use the string similarity join as before to find a set of entities that have some overlap in the values of the important columns. Before doing that, we need to transform the columns that are part of the mixture to strings. The py_stringsimjoin package allows us to do so easily.

In [122]:
# creates a string composed of different columns, to facilitate string comparison (matching pairs)

# transforming the "budget" column into string and creating a new **mixture** column
ssj.utils.converter.dataframe_column_to_str(imdb_data, 'budget', inplace=True)
imdb_data['mixture'] = imdb_data['norm_title'] + ' ' + imdb_data['norm_year'] + ' ' + imdb_data['budget']

# repeating the same thing for the Kaggle dataset
ssj.utils.converter.dataframe_column_to_str(kaggle_data, 'budget', inplace=True)
kaggle_data['mixture'] = kaggle_data['norm_movie_title'] + ' ' + kaggle_data['norm_title_year'] + ' ' + kaggle_data['budget']

Now, we can use the mixture columns to create a desired candidate set which we call C.

In [123]:
C = ssj.overlap_coefficient_join(kaggle_data, imdb_data, 'id', 'id', 'mixture', 'mixture', sm.WhitespaceTokenizer(), l_out_attrs=['norm_movie_title', 'norm_title_year', 'duration', 'budget', 'content_rating'], r_out_attrs=['norm_title', 'norm_year', 'length', 'budget', 'mpaa'], threshold=0.65)

print(C)

0% [##############################] 100% | ETA: 00:00:00

         _id  l_id    r_id              l_norm_movie_title l_norm_title_year  \
0          0  4841      99            dude  wheres my dog!              2014
1          1  4337     106                       road hard              2015
2          2  4342     106           me you and five bucks              2015
3          3  4351     106                       checkmate              2015
4          4  4352     106                         #horror              2015
5          5  4871     183            the image revolution              2014
6          6  3429     288           house of 1000 corpses              2003
7          7  4029     368                       compadres              2016
8          8  2726     450             crocodile dundee ii              1988
9          9  4775     630                            burn              2012
10        10  4471     733                         orgazmo              1997
11        11  3406     838              500 days of summer              2009
12        12  4833     969               facing the giants              2006
13        13  4720    1135                  wendy and lucy              2008
14        14  4788    1135                 call + response              2008
15        15  3172    1429                       severance              2006
16        16  3650    1429                       clerks ii              2006
17        17  3716    1429                  the oh in ohio              2006
18        18  4172    1469                      courageous              2011
19        19  4894    1497                        flywheel              2003
20        20  4482    1508           taxi to the dark side              2007
21        21  4301    1563                         caramel              2007
22        22  4860    1648                        absentia              2011
23        23  2965    1851           10 days in a madhouse              2015
24        24  2634    1872                           keanu              2016
25        25  3631    1872             10 cloverfield lane              2016
26        26  2965    1881           10 days in a madhouse              2015
27        27  2965    1883           10 days in a madhouse              2015
28        28  2799    1964      10 things i hate about you              1999
29        29  4140    2034                          8 days              2014
...      ...   ...     ...                             ...               ...
18287  18287  3872  868572                           adore              2013
18288  18288  4879  868714                  run  hide  die              2012
18289  18289  4140  868775                          8 days              2014
18290  18290  1705  868851              doa: dead or alive              2006
18291  18291  2094  868851                      black book              2006
18292  18292  4194  869168                        shortbus              2006
18293  18293  4223  869168                      sherrybaby              2006
18294  18294  4661  869280             fight to the finish              2016
18295  18295  1338  869396          paul blart: mall cop 2              2015
18296  18296  1452  869396  the x files: i want to believe              2008
18297  18297  1620  869396                 p.s. i love you              2007
18298  18298  1628  869396                         sicario              2015
18299  18299  1629  869396                        southpaw              2015
18300  18300  1709  869396                       wild card              2015
18301  18301  1715  869396                 a warriors tail              2015
18302  18302  1949  869396                          legend              2015
18303  18303  2405  869396                      steve jobs              2015
18304  18304  4892  869446                     dutch kills              2015
18305  18305  4898  869573            stories of our lives              2014
18306  18306  4358  869577                   the dog lover              2016
18307  18307  4868  869630             the call of cthulhu              2005
18308  18308  4848  869658  the past is a grotesque animal              2014
18309  18309  4858  869658                    tiger orange              2014
18310  18310  4609  869691                  the maids room              2013
18311  18311   579  869787                             xxx              2002
18312  18312   606  869787                     bad company              2002
18313  18313   608  869787                           i spy              2002
18314  18314   613  869787                      rollerball              2002
18315  18315   614  869787       ballistic: ecks vs. sever              2002
18316  18316   782  869790         xxx: state of the union              2005

       l_duration  l_budget l_content_rating                r_norm_title  \
0            82.0     20000               PG                     #hacked
1            98.0   1500000              NaN                     #horror
2            93.0   1500000              NaN                     #horror
3            97.0   1500000              NaN                     #horror
4           101.0   1500000        Not Rated                     #horror
5            81.0     50000              NaN                   #sosingle
6           105.0   7000000                R                         $18
7           101.0   3000000                R                          76
8           108.0  15800000               PG         crocodile dundee ii
9            86.0    225000        Not Rated                        oops
10           92.0   1000000            NC-17           til there was you
11           95.0   7500000            PG-13        (500) days of summer
12          111.0    100000               PG                 (s)election
13           80.0    200000                R                   ...around
14           86.0    200000            PG-13                   ...around
15           90.0   5000000                R                         .45
16           97.0   5000000                R                         .45
17           88.0   5000000                R                         .45
18          129.0   2000000            PG-13           00 - zero zero 3d
19          120.0     20000              NaN                         008
20           53.0   1000000                R                    00:01:18
21           95.0   1300000               PG           07-y menyaet kurs
22           87.0     70000                R                    1 minute
23          111.0  12000000                R                          10
24          100.0  15000000                R         10 cloverfield lane
25          104.0  15000000            PG-13         10 cloverfield lane
26          111.0  12000000                R         10 days in delaware
27          111.0  12000000                R       10 days in a madhouse
28           97.0  16000000            PG-13  10 things i hate about you
29           90.0   2500000            PG-13                 10 000 days
...           ...       ...              ...                         ...
18287       112.0  16000000                R                        zulu
18288        75.0     50000              NaN                   zuretzako
18289        90.0   2500000            PG-13                      zvezda
18290        87.0  21000000            PG-13                   zwartboek
18291       145.0  21000000                R                   zwartboek
18292       101.0   2000000          Unrated                   zyzzyx rd
18293        96.0   2000000                R                   zyzzyx rd
18294        94.0    150000            PG-13                   decanted.
18295        94.0  30000000               PG                           i
18296       108.0  30000000            PG-13                           i
18297       126.0  30000000            PG-13                           i
18298       121.0  30000000                R                           i
18299       124.0  30000000                R                           i
18300        92.0  30000000                R                           i
18301        85.0  30000000              NaN                           i
18302       132.0  30000000                R                           i
18303       122.0  30000000                R                           i
18304        90.0     25000              NaN                 igirlfriend
18305        60.0     15000              NaN                    mfistula
18306       101.0   2000000               PG                         mba
18307        47.0     50000              NaN                      r3tual
18308        77.0    100000          Unrated                  skidnapped
18309        75.0    100000          Unrated                  skidnapped
18310        98.0    600000              NaN                      sxtape
18311       132.0  70000000            PG-13                         xxx
18312       116.0  70000000            PG-13                         xxx
18313        97.0  70000000            PG-13                         xxx
18314        98.0  70000000                R                         xxx
18315        91.0  70000000                R                         xxx
18316       101.0  87000000            PG-13     xxx: state of the union

      r_norm_year  r_length  r_budget r_mpaa  _sim_score
0            2014       NaN     20000    NaN    0.666667
1            2015     101.0   1500000    NaN    0.666667
2            2015     101.0   1500000    NaN    0.666667
3            2015     101.0   1500000    NaN    0.666667
4            2015     101.0   1500000    NaN    1.000000
5            2014       NaN     50000    NaN    0.666667
6            2003      15.0      1000    NaN    0.666667
7            2016     118.0   3000000    NaN    0.666667
8            1988     108.0  14000000    NaN    0.800000
9            2012       5.0    225000    NaN    0.666667
10           1997     113.0   1000000  PG-13    0.666667
11           2009      95.0   7500000  PG-13    0.833333
12           2006      59.0    100000    NaN    0.666667
13           2008     104.0    200000    NaN    0.666667
14           2008     104.0    200000    NaN    0.666667
15           2006     101.0   5000000      R    0.666667
16           2006     101.0   5000000      R    0.666667
17           2006     101.0   5000000      R    0.666667
18           2011      75.0   2000000    NaN    0.666667
19           2003       7.0     20000    NaN    0.666667
20           2007       NaN   1000000    NaN    0.666667
21           2007      91.0   1300000    NaN    0.666667
22           2011       NaN     70000    NaN    0.666667
23           2015      90.0         0    NaN    0.666667
24           2016     104.0  15000000  PG-13    0.666667
25           2016     104.0  15000000  PG-13    1.000000
26           2015       NaN         0    NaN    0.666667
27           2015     111.0  12000000      R    1.000000
28           1999      97.0  16000000  PG-13    1.000000
29           2014      91.0   2500000    NaN    0.750000
...           ...       ...       ...    ...         ...
18287        2013     110.0  16000000      R    0.666667
18288        2012      45.0     50000    NaN    0.666667
18289        2014     128.0   2500000    NaN    0.666667
18290        2006     145.0  21000000      R    0.666667
18291        2006     145.0  21000000      R    0.666667
18292        2006      90.0   2000000    NaN    0.666667
18293        2006      90.0   2000000    NaN    0.666667
18294        2016      82.0    150000    NaN    0.666667
18295        2015     188.0  30000000    NaN    0.666667
18296        2015     188.0  30000000    NaN    0.666667
18297        2015     188.0  30000000    NaN    0.666667
18298        2015     188.0  30000000    NaN    0.666667
18299        2015     188.0  30000000    NaN    0.666667
18300        2015     188.0  30000000    NaN    0.666667
18301        2015     188.0  30000000    NaN    0.666667
18302        2015     188.0  30000000    NaN    0.666667
18303        2015     188.0  30000000    NaN    0.666667
18304        2015      85.0     25000    NaN    0.666667
18305        2014       NaN     15000    NaN    0.666667
18306        2016       NaN   2000000    NaN    0.666667
18307        2005      90.0     50000    NaN    0.666667
18308        2014       NaN    100000    NaN    0.666667
18309        2014       NaN    100000    NaN    0.666667
18310        2013      82.0    600000    NaN    0.666667
18311        2002     132.0  70000000  PG-13    1.000000
18312        2002     132.0  70000000  PG-13    0.666667
18313        2002     132.0  70000000  PG-13    0.666667
18314        2002     132.0  70000000  PG-13    0.666667
18315        2002     132.0  70000000  PG-13    0.666667
18316        2005     101.0  87000000  PG-13    1.000000

[18317 rows x 14 columns]

Total time elapsed: 00:00:12

We can see that by doing a similarity join, we already reduced the candidate set to 18,317 pairs.

#### Substep B: Specifying the keys

The next step is to specify to the py_entitymatching package which columns correspond to the keys in each dataframe. Also, we need to specify which columns correspond to the foreign keys of the the two dataframes in the candidate set.

In [124]:
# had to run on terminal:
# condal install -c conda-forge py_entitymatching

In [125]:
import py_entitymatching as em
em.set_key(kaggle_data, 'id')   # specifying the key column in the kaggle dataset
em.set_key(imdb_data, 'id')     # specifying the key column in the imdb dataset
em.set_key(C, '_id')            # specifying the key in the candidate set
em.set_ltable(C, kaggle_data)   # specifying the left table 
em.set_rtable(C, imdb_data)     # specifying the right table
em.set_fk_rtable(C, 'r_id')     # specifying the column that matches the key in the right table 
em.set_fk_ltable(C, 'l_id')     # specifying the column that matches the key in the left table

True

#### Substep C: Debugging the blocker

Now, we need to make sure that the candidate set is loose enough to include pairs of movies that are not very close. If this is not the case, there is a chance that we have eliminated pair that could be potentially matched together. By looking at a few pairs from the candidate set, we can judge whether the blocking step has been too harsh or not.

Note: The py_entitymatching package provides some tools for debugging the blocker as well.

In [126]:
C[['l_norm_movie_title', 'r_norm_title', 'l_norm_title_year', 'r_norm_year',
   'l_budget', 'r_budget', 'l_content_rating', 'r_mpaa']].head()

,l_norm_movie_title,r_norm_title,l_norm_title_year,r_norm_year,l_budget,r_budget,l_content_rating,r_mpaa
0,dude wheres my dog!,#hacked,2014,2014,20000,20000,PG,NaN
1,road hard,#horror,2015,2015,1500000,1500000,NaN,NaN
2,me you and five bucks,#horror,2015,2015,1500000,1500000,NaN,NaN
3,checkmate,#horror,2015,2015,1500000,1500000,NaN,NaN
4,#horror,#horror,2015,2015,1500000,1500000,Not Rated,NaN

#### Substep D: Sampling from the candidate set

The goal of this step is to obtain a sample from the candidate set and manually label the sampled candidates; that is, to specify if the candidate pair is a correct match or not.

In [127]:
# Sampling 500 pairs
sampled = C.sample(500, random_state=0)
sampled.to_csv('./data/sampled.csv', encoding='utf-8')

In order to label the sampled data, we can create a new column in the .csv file (which we call label) and put value 1 under that column if the pair is a correct match and 0 otherwise. To avoid overriding the files, let’s rename the new file as labeled.csv.

In [128]:
# response = urllib.request.urlretrieve('https://anaconda.org/BigGorilla/datasets/1/download/labeled.csv', './data/labeled.csv')

import urllib.request
url = "https://anaconda.org/BigGorilla/datasets/1/download/labeled.csv"
#hdr = { 'User-Agent' : 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)' }
opener = urllib.request.build_opener()
opener.addheaders = [['User-agent', 'Mozilla/5.0']]
urllib.request.install_opener(opener)

#req = urllib.request.Request(url, headers=hdr)
response = urllib.request.urlretrieve(url, './data/labeled.csv')

In [129]:
labeled = em.read_csv_metadata('./data/labeled.csv', ltable=kaggle_data, rtable=imdb_data, fk_ltable='l_id', fk_rtable='r_id', key='_id')
labeled.head()

Metadata file is not present in the given path; proceeding to read the csv file.

,Unnamed: 0,_id,l_id,r_id,l_norm_movie_title,l_norm_title_year,l_duration,l_budget,l_content_rating,r_norm_title,r_norm_year,r_length,r_budget,r_mpaa,_sim_score,label
0,4771,4771,2639,235925,eye of the beholder,1999,109.0,15000000,R,eye of the beholder,1999,109.0,35000000,R,0.833333,1
1,11478,11478,2001,600301,rocky balboa,2006,139.0,24000000,PG,rocky balboa,2006,139.0,24000000,PG,1.000000,1
2,13630,13630,4160,691766,from russia with love,1963,115.0,2000000,Approved,the aeolians: from russia with love,2012,NaN,20000,NaN,0.666667,0
3,1972,1972,1248,101029,sex tape,2014,94.0,40000000,R,blended,2014,117.0,40000000,PG-13,0.666667,0
4,15903,15903,722,758133,the scorch trials,2015,132.0,61000000,PG-13,the scorch trials,2015,132.0,61000000,PG-13,1.000000,1

#### Substep E: Traning machine learning algorithms

In [130]:
# We use the sampled dataset to train various machine learning algorithms for our prediction task.

#Split our dataset into a training and a test set, 
# and then select the desired machine learning technique for our prediction task

split = em.split_train_test(labeled, train_proportion=0.5, random_state=0)
train_data = split['train']
test_data = split['test']

dt = em.DTMatcher(name='DecisionTree', random_state=0)
svm = em.SVMMatcher(name='SVM', random_state=0)
rf = em.RFMatcher(name='RF', random_state=0)
lg = em.LogRegMatcher(name='LogReg', random_state=0)
ln = em.LinRegMatcher(name='LinReg')
nb = em.NBMatcher(name='NaiveBayes')

Before we can apply any machine learning technique, we need to extract a set of features. Fortunately, the py_entitymatching package can automatically extract a set of features once we specify which columns in the two datasets correspond to each other. The following code snippet starts by specifying the correspondence between the column of the two datasets. Then, it uses the py_entitymatching package to determine the type of each column. By considering the types of columns in each dataset (stored in variables l_attr_types and r_attr_types), and using the tokenizers and similarity functions suggested by the package, we can extract a set of instructions for extracting features. Note that variable F is not the set of extracted features, rather it encodes the instructions for computing the features.

In [131]:
attr_corres = em.get_attr_corres(kaggle_data, imdb_data)
    # type(attr_corres)  => dict
attr_corres['corres'] = [('norm_movie_title', 'norm_title'),
                        ('norm_title_year', 'norm_year'),
                        ('content_rating', 'mpaa'),
                        ('budget', 'budget'),
                       ]
    # type(attr_corres['corres']) => list

l_attr_types = em.get_attr_types(kaggle_data)   
    # dict, ie norm_movie_title, norm_title'year, budget, etc.
r_attr_types = em.get_attr_types(imdb_data)   # dict

tok = em.get_tokenizers_for_matching() # dict
sim = em.get_sim_funs_for_matching() # dict

F = em.get_features(kaggle_data, imdb_data, l_attr_types, r_attr_types, attr_corres, tok, sim)
# type(F) pandas.core.frame.DataFrame

# print(F)

Given the set of desired features F, we can now calculate the feature values for our training data and also impute the missing values in our data. In this case, we choose to replace the missing values with the mean of the column.

In [132]:
train_features = em.extract_feature_vecs(train_data, feature_table=F, attrs_after='label', show_progress=False)
train_features = em.impute_table(train_features, exclude_attrs=['_id', 'l_id', 'r_id', 'label'], strategy='mean')

/Users/macbookpro/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

Using the calculated features, we can evaluate the performance of different machine learning algorithms and select the best one for our matching task

In [133]:
# help(em.select_matcher)

In [134]:
result = em.select_matcher([dt, rf, svm, ln, lg, nb], table=train_features, exclude_attrs=['_id', 'l_id', 'r_id', 'label'], k=5, target_attr='label', metrics_to_display='f1', random_state=0)
    # had to change the argument 'metric' to 'metrics_to_display'
result['cv_stats']

        Matcher  Average f1
0  DecisionTree    0.701211
1            RF    0.688889
2           SVM    0.162198
3        LinReg    0.738423
4        LogReg    0.468584
5    NaiveBayes    0.459578

#### Substep F: Evaluating the quality of our matching

In [135]:
# We are obtaining a high accurracy and recall on the test set as well.b


best_model = result['selected_matcher']
best_model.fit(table=train_features, exclude_attrs=['_id', 'l_id', 'r_id', 'label'], target_attr='label')

test_features = em.extract_feature_vecs(test_data, feature_table=F, attrs_after='label', show_progress=False)
test_features = em.impute_table(test_features, exclude_attrs=['_id', 'l_id', 'r_id', 'label'], strategy='mean')

# Predict on the test data
predictions = best_model.predict(table=test_features, exclude_attrs=['_id', 'l_id', 'r_id', 'label'], 
								 append=True, target_attr='predicted', inplace=False)

# Evaluate the predictions
eval_result = em.eval_matches(predictions, 'label', 'predicted')

/Users/macbookpro/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

#### Substep G: Using the trained model to match the datasets

In [136]:
# match the 2 tables using the trained model

candset_features = em.extract_feature_vecs(C, feature_table=F, show_progress=True)
candset_features = em.impute_table(candset_features, exclude_attrs=['_id', 'l_id', 'r_id'], strategy='mean')
predictions = best_model.predict(table=candset_features, exclude_attrs=['_id', 'l_id', 'r_id'], append=True, target_attr='predicted', inplace=False)
matches = predictions[predictions.predicted == 1]

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:38
/Users/macbookpro/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [137]:
# remove all unecessary columns, 
# creates a well-formatted dataframe that has the resulting integrated dataset

from py_entitymatching.catalog import catalog_manager as cm
matches = matches[['_id', 'l_id', 'r_id', 'predicted']]
matches.reset_index(drop=True, inplace=True)
cm.set_candset_properties(matches, '_id', 'l_id', 'r_id', kaggle_data, imdb_data)
matches = em.add_output_attributes(matches, l_output_attrs=['norm_movie_title', 'norm_title_year', 'budget', 'content_rating'], r_output_attrs=['norm_title', 'norm_year', 'budget', 'mpaa'], l_output_prefix='l_', r_output_prefix='r_', delete_from_catalog=False)
matches.drop('predicted', axis=1, inplace=True)
matches.head()

,_id,l_id,r_id,l_norm_movie_title,l_norm_title_year,l_budget,l_content_rating,r_norm_title,r_norm_year,r_budget,r_mpaa
0,4,4352,106,#horror,2015,1500000,Not Rated,#horror,2015,1500000,NaN
1,8,2726,450,crocodile dundee ii,1988,15800000,PG,crocodile dundee ii,1988,14000000,NaN
2,11,3406,838,500 days of summer,2009,7500000,PG-13,(500) days of summer,2009,7500000,PG-13
3,25,3631,1872,10 cloverfield lane,2016,15000000,PG-13,10 cloverfield lane,2016,15000000,PG-13
4,26,2965,1881,10 days in a madhouse,2015,12000000,R,10 days in delaware,2015,0,NaN

Question durant le tutoriel:

De faire un simple 'merge' sur 2 tables représentant les mêmes données ne donnera pas le résultat escompté. On rencontrera le problème d'inconsistence des données, alors que par exemple si on fait un joins sur une colonne par nom, en espérant qu'un 'Michel' et un 'michel', ou un 'MICHEL' (etc.) soit 'merged', cela ne fonctionnera pas, car les 2 strings ne sont pas équivalentes. On doit donc commencer par nettoyer les données en, par exemple, les uniformisant. Il s'agira de s'assurer que les É et les E, ou les majuscules et minuscules ne soient pas distinguées, si c'est ce que l'on veut. Aussi, de s'assurer que les unités de mesure (ex. cm vs pouce) soit les mêmes entre les 2 tables.

RÉSUMÉ:

J'ai appris la différence entre un simple merge, d'utiliser la edit distance sur des strings, et d'utiliser l'apprentissage machine pour matcher des entités. 
Il va de soi que l'efficacité est progressive (la plus efficace étant l'apprentissage machine), comparatifs, statistiques et nombres de rows résultants à l'appui.