<p style='text-align: right;'> Plotting and Programming in Python </p>

# Reading Tabular Data into DataFrames

### Q: Reading Other Data

Read the data in gapminder_gdp_americas.csv (which should be in the same directory as gapminder_gdp_oceania.csv) into a variable called americas and display its summary statistics.

In [3]:
import pandas as pd

americas = pd.read_csv('data/gapminder_gdp_americas.csv', index_col='country')
print(americas)

                    continent  gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  \
country
Argentina            Americas     5911.315053     6856.856212     7133.166023
Bolivia              Americas     2677.326347     2127.686326     2180.972546
Brazil               Americas     2108.944355     2487.365989     3336.585802
Canada               Americas    11367.161120    12489.950060    13462.485550
Chile                Americas     3939.978789     4315.622723     4519.094331
Colombia             Americas     2144.115096     2323.805581     2492.351109
Costa Rica           Americas     2627.009471     2990.010802     3460.937025
Cuba                 Americas     5586.538780     6092.174359     5180.755910
Dominican Republic   Americas     1397.717137     1544.402995     1662.137359
Ecuador              Americas     3522.110717     3780.546651     4086.114078
El Salvador          Americas     3048.302900     3421.523218     3776.803627
Guatemala            Americas     2428.237769     2617.155967     2750.364446
Haiti                Americas     1840.366939     1726.887882     1796.589032
Honduras             Americas     2194.926204     2220.487682     2291.156835
Jamaica              Americas     2898.530881     4756.525781     5246.107524
Mexico               Americas     3478.125529     4131.546641     4581.609385
Nicaragua            Americas     3112.363948     3457.415947     3634.364406
Panama               Americas     2480.380334     2961.800905     3536.540301
Paraguay             Americas     1952.308701     2046.154706     2148.027146
Peru                 Americas     3758.523437     4245.256698     4957.037982
Puerto Rico          Americas     3081.959785     3907.156189     5108.344630
Trinidad and Tobago  Americas     3023.271928     4100.393400     4997.523971
United States        Americas    13990.482080    14847.127120    16173.145860
Uruguay              Americas     5716.766744     6150.772969     5603.357717
Venezuela            Americas     7689.799761     9802.466526     8422.974165

                     gdpPercap_1967  gdpPercap_1972  gdpPercap_1977  \
country
Argentina               8052.953021     9443.038526    10079.026740
Bolivia                 2586.886053     2980.331339     3548.097832
Brazil                  3429.864357     4985.711467     6660.118654
Canada                 16076.588030    18970.570860    22090.883060
Chile                   5106.654313     5494.024437     4756.763836
Colombia                2678.729839     3264.660041     3815.807870
Costa Rica              4161.727834     5118.146939     5926.876967
Cuba                    5690.268015     5305.445256     6380.494966
Dominican Republic      1653.723003     2189.874499     2681.988900
Ecuador                 4579.074215     5280.994710     6679.623260
El Salvador             4358.595393     4520.246008     5138.922374
Guatemala               3242.531147     4031.408271     4879.992748
Haiti                   1452.057666     1654.456946     1874.298931
Honduras                2538.269358     2529.842345     3203.208066
Jamaica                 6124.703451     7433.889293     6650.195573
Mexico                  5754.733883     6809.406690     7674.929108
Nicaragua               4643.393534     4688.593267     5486.371089
Panama                  4421.009084     5364.249663     5351.912144
Paraguay                2299.376311     2523.337977     3248.373311
Peru                    5788.093330     5937.827283     6281.290855
Puerto Rico             6929.277714     9123.041742     9770.524921
Trinidad and Tobago     5621.368472     6619.551419     7899.554209
United States          19530.365570    21806.035940    24072.632130
Uruguay                 5444.619620     5703.408898     6504.339663
Venezuela               9541.474188    10505.259660    13143.950950

                     gdpPercap_1982  gdpPercap_1987  gdpPercap_1992  \
country
Argentina               8997.897412     9139.671389     9308.418710
Bolivia                 3156.510452     2753.691490     2961.699694
Brazil                  7030.835878     7807.095818     6950.283021
Canada                 22898.792140    26626.515030    26342.884260
Chile                   5095.665738     5547.063754     7596.125964
Colombia                4397.575659     4903.219100     5444.648617
Costa Rica              5262.734751     5629.915318     6160.416317
Cuba                    7316.918107     7532.924763     5592.843963
Dominican Republic      2861.092386     2899.842175     3044.214214
Ecuador                 7213.791267     6481.776993     7103.702595
El Salvador             4098.344175     4140.442097     4444.231700
Guatemala               4820.494790     4246.485974     4439.450840
Haiti                   2011.159549     1823.015995     1456.309517
Honduras                3121.760794     3023.096699     3081.694603
Jamaica                 6068.051350     6351.237495     7404.923685
Mexico                  9611.147541     8688.156003     9472.384295
Nicaragua               3470.338156     2955.984375     2170.151724
Panama                  7009.601598     7034.779161     6618.743050
Paraguay                4258.503604     3998.875695     4196.411078
Peru                    6434.501797     6360.943444     4446.380924
Puerto Rico            10330.989150    12281.341910    14641.587110
Trinidad and Tobago     9119.528607     7388.597823     7370.990932
United States          25009.559140    29884.350410    32003.932240
Uruguay                 6920.223051     7452.398969     8137.004775
Venezuela              11152.410110     9883.584648    10733.926310

                     gdpPercap_1997  gdpPercap_2002  gdpPercap_2007
country
Argentina              10967.281950     8797.640716    12779.379640
Bolivia                 3326.143191     3413.262690     3822.137084
Brazil                  7957.980824     8131.212843     9065.800825
Canada                 28954.925890    33328.965070    36319.235010
Chile                  10118.053180    10778.783850    13171.638850
Colombia                6117.361746     5755.259962     7006.580419
Costa Rica              6677.045314     7723.447195     9645.061420
Cuba                    5431.990415     6340.646683     8948.102923
Dominican Republic      3614.101285     4563.808154     6025.374752
Ecuador                 7429.455877     5773.044512     6873.262326
El Salvador             5154.825496     5351.568666     5728.353514
Guatemala               4684.313807     4858.347495     5186.050003
Haiti                   1341.726931     1270.364932     1201.637154
Honduras                3160.454906     3099.728660     3548.330846
Jamaica                 7121.924704     6994.774861     7320.880262
Mexico                  9767.297530    10742.440530    11977.574960
Nicaragua               2253.023004     2474.548819     2749.320965
Panama                  7113.692252     7356.031934     9809.185636
Paraguay                4247.400261     3783.674243     4172.838464
Peru                    5838.347657     5909.020073     7408.905561
Puerto Rico            16999.433300    18855.606180    19328.709010
Trinidad and Tobago     8792.573126    11460.600230    18008.509240
United States          35767.433030    39097.099550    42951.653090
Uruguay                 9230.240708     7727.002004    10611.462990
Venezuela              10165.495180     8605.047831    11415.805690

### Q: Inspecting Data

After reading the data for the Americas, use help(americas.head) and help(americas.tail) to find out what DataFrame.head and DataFrame.tail do.

    1. What method call will display the first three rows of this data?
    2. What method call will display the last three columns of this data? (Hint: you may need to change your view of the data.)

In [7]:
help(americas.head)

Help on method head in module pandas.core.generic:

head(n=5) method of pandas.core.frame.DataFrame instance
    Return the first `n` rows.

    This function returns the first `n` rows for the object based
    on position. It is useful for quickly testing if your object
    has the right type of data in it.

    Parameters
    ----------
    n : int, default 5
        Number of rows to select.

    Returns
    -------
    obj_head : same type as caller
        The first `n` rows of the caller object.

    See Also
    --------
    DataFrame.tail: Returns the last `n` rows.

    Examples
    --------
    >>> df = pd.DataFrame({'animal':['alligator', 'bee', 'falcon', 'lion',
    ...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
    >>> df
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot
    6      shark
    7      whale
    8      zebra

    Viewing the first 5 lines

    >>> df.head()
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey

    Viewing the first `n` lines (three in this case)

    >>> df.head(3)
          animal
    0  alligator
    1        bee
    2     falcon

In [15]:
# 1. What method call will display the first three rows of this data?
americas.head(n=3)  # or americas.head(3)

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,,
Argentina,Americas,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
Bolivia,Americas,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
Brazil,Americas,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825

In [13]:
# 2. What method call will display the last three columns of this data? 
# (Hint: you may need to change your view of the data.)
americas.T.tail(n=3)  # or americas.T.tail(3)

country,Argentina,Bolivia,Brazil,Canada,Chile,Colombia,Costa Rica,Cuba,Dominican Republic,Ecuador,...,Mexico,Nicaragua,Panama,Paraguay,Peru,Puerto Rico,Trinidad and Tobago,United States,Uruguay,Venezuela
gdpPercap_1997,10967.3,3326.14,7957.98,28954.9,10118.1,6117.36,6677.05,5431.99,3614.1,7429.46,...,9767.3,2253.02,7113.69,4247.4,5838.35,16999.4,8792.57,35767.4,9230.24,10165.5
gdpPercap_2002,8797.64,3413.26,8131.21,33329,10778.8,5755.26,7723.45,6340.65,4563.81,5773.04,...,10742.4,2474.55,7356.03,3783.67,5909.02,18855.6,11460.6,39097.1,7727,8605.05
gdpPercap_2007,12779.4,3822.14,9065.8,36319.2,13171.6,7006.58,9645.06,8948.1,6025.37,6873.26,...,11977.6,2749.32,9809.19,4172.84,7408.91,19328.7,18008.5,42951.7,10611.5,11415.8

### Q: Reading files in Other Directories

The data for your current project is stored in a file called microbes.csv, which is located in a folder called field_data. You are doing analysis in a notebook called analysis.ipynb in a sibling folder called thesis:

your_home_directory
+-- field_data/
|   +-- microbes.csv
+-- thesis/
    +-- analysis.ipynb

What value(s) should you pass to read_csv to read microbes.csv in analysis.ipynb?

In [ ]:
import pandas as pd
data = pd.read_csv('../field_data/microbes.csv')

### Q: Writing Data

As well as the read_csv function for reading data from a file, Pandas provides a to_csv function to write dataframes to files. Applying what you’ve learned about reading from files, write one of your dataframes to a file called processed.csv. You can use help to get information on how to use to_csv.

In [27]:
import pandas
help(pandas.DataFrame.to_csv)

Help on function to_csv in module pandas.core.generic:

to_csv(self, path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression='infer', quoting=None, quotechar='"', line_terminator=None, chunksize=None, tupleize_cols=None, date_format=None, doublequote=True, escapechar=None, decimal='.')
    Write object to a comma-separated values (csv) file.

    .. versionchanged:: 0.24.0
        The order of arguments for Series was changed.

    Parameters
    ----------
    path_or_buf : str or file handle, default None
        File path or object, if None is provided the result is returned as
        a string.  If a file object is passed it should be opened with
        `newline=''`, disabling universal newlines.

        .. versionchanged:: 0.24.0

           Was previously named "path" for Series.

    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, default None
        Format string for floating point numbers.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.

        .. versionchanged:: 0.24.0

           Previously defaulted to False for Series.

    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : str
        Python write mode, default 'w'.
    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'ascii' on Python 2 and 'utf-8' on Python 3.
    compression : str, default 'infer'
        Compression mode among the following possible values: {'infer',
        'gzip', 'bz2', 'zip', 'xz', None}. If 'infer' and `path_or_buf`
        is path-like, then detect compression from the following
        extensions: '.gz', '.bz2', '.zip' or '.xz'. (otherwise no
        compression).

        .. versionchanged:: 0.24.0

           'infer' option added and set to default.

    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    line_terminator : string, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\n' for linux, '\r\n' for Windows, i.e.).

        .. versionchanged:: 0.24.0
    chunksize : int or None
        Rows to write at a time.
    tupleize_cols : bool, default False
        Write MultiIndex columns as a list of tuples (if True) or in
        the new, expanded format, where each MultiIndex column is a row
        in the CSV (if False).

        .. deprecated:: 0.21.0
           This argument will be removed and will always write each row
           of the multi-index as a separate row in the CSV file.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Load an Excel file into a DataFrame.

    Examples
    --------
    >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
    ...                    'mask': ['red', 'purple'],
    ...                    'weapon': ['sai', 'bo staff']})
    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'

Note that help(to_csv) throws an error! This is a subtlety and is due to the fact that to_csv is NOT a function in and of itself and the actual call is americas.to_csv.

In [28]:
americas.to_csv('processed.csv')